console.log("This is about more methods in array")
let  a = [1,2,3,4,5]
let b = (a.toString())
console.log(b)
let c = (a.join(" & "))
console.log(c)
let d = (a.pop())
console.log(a)
let e = (a.push(12))
console.log(a)
let f = (a.shift())
console.log(a)
let g = (a.unshift(45))
console.log(a)